# filetype groups to simplify data output


filetypetags = {
                "7zip Archive": "7zip",
                "Adobe Flash File": "Flash",
                "Android APK": "Android",
                "Android DEX": "Android",
                "Apple's Universal binary file": "MacOSX",
                "DLL": "DLL",
                "DLL64": "DLL",
                "ELF": "ELF",
                "Email Link": "Email",
                "JAVA Class": "JAVA",
                "JAVA JAR": "Java",
                "Link": "Link",
                "Mac OS X app bundle in ZIP archive": "MacOSX",
                "Mac OS X app installer": "MacOSX",
                "MacOSX DMG": "MacOSX",
                "Mach-O": "MacOSX",
                "Macro": "Macro",
                "Microsoft Excel 97 - 2003 Document": "Excel",
                "Microsoft Excel Document": "Excel",
                "Microsoft PowerPoint 97 - 2003 Document": "Powerpoint",
                "Microsoft PowerPoint Document": "Powerpoint",
                "Microsoft Word 97 - 2003 Document": "Word",
                "Microsoft Word Document": "Word",
                "PDF": "PDF",
                "PE": "PE",
                "PE64": "PE",
                "RAR Archive": "RAR Archive",
                "RTF": "RTF",
        }
